name: Cleanup Unused Actions

on:
  schedule:
    - cron: '0 0 * * 0' # Ejecutar cada domingo a medianoche
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Cleanup Unused Docker Images
      run: |
        docker image prune -af

    - name: Cleanup Unused Docker Containers
      run: |
        docker container prune -f

    - name: Cleanup Unused GitHub Actions Runners
      run: |
        sudo rm -rf /opt/hostedtoolcache/*

    - name: Cleanup Unused Dependencies
      run: |
        npm cache clean --force
        yarn cache clean
        pip cache purge
        rm -rf node_modules
        rm -rf ~/.cache/pip

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Cleanup unused actions and dependencies"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

